# Run with:
# --> docker-compose --file docker-compose-express.yml up --build

version: "3.8"

services:
  express:
    container_name: express_jwt_app
    build:
      context: ./app/
    env_file:
      # Remember to have the ".env" configured
      - ./app/.env
    ports:
      - "${APP_PORT}:${APP_PORT}" # from .env file
    networks:
      - docker_apis_and_apps

networks:
  docker_apis_and_apps:
    driver: bridge
    name: docker_apis_and_apps
